# Generated by Django 6.0 on 2025-12-14 12:33

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('farm_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('city_or_region', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Farmer',
                'verbose_name_plural': 'Farmers',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('size_in_hectares', models.FloatField()),
                ('soil_type', models.CharField(blank=True, max_length=50)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, choices=[('planted', 'Planted'), ('growing', 'Growing'), ('ready ', 'Ready for harvest'), ('harvested', 'Harvested')], default='planted', max_length=20)),
                ('planted_on', models.DateField(default=datetime.date.today)),
                ('expected_harvest', models.DateField(blank=True, null=True)),
                ('fields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='agri_app.field')),
            ],
            options={
                'ordering': ['-planted_on'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Planting, Fertilizing, Scouting, Harvesting', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed notes on the task.')),
                ('scheduled_date', models.DateField(help_text='The date the activity is scheduled or completed.')),
                ('estimated_harvest_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='scheduled', max_length=20)),
                ('farmer', models.ForeignKey(help_text='The farmer/user who scheduled this activity.', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='agri_app.crop')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='agri_app.field')),
            ],
            options={
                'verbose_name': 'Scheduled Activity',
                'verbose_name_plural': 'Scheduled Activities',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='SecureRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(help_text="A descriptive name for the route (e.g., 'Farm to Goma Market').", max_length=100)),
                ('route_path_geojson', models.TextField(help_text='The geographical data (GeoJSON) defining the route path for map display.')),
                ('security_status', models.CharField(choices=[('green', 'Safe (Low Risk)'), ('yellow', 'Caution (Medium Risk)'), ('red', 'Unsafe (High Risk / Blocked)')], default='yellow', help_text='The assessed security level for the route.', max_length=10)),
                ('risk_notes', models.TextField(blank=True, help_text='Details on security threats or blockages.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(help_text='The user who created or last updated this route.', on_delete=django.db.models.deletion.CASCADE, related_name='secure_routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Secure Transport Route',
                'verbose_name_plural': 'Secure Transport Routes',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time the reading was taken.')),
                ('location', models.CharField(blank=True, help_text='City or specific GPS reference.', max_length=100)),
                ('temperature', models.FloatField(help_text='Temperature in °C.')),
                ('humidity', models.FloatField(help_text='Humidity percentage (0-100).')),
                ('rainfall', models.FloatField(help_text='Rainfall/precipitation in millimeters.')),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='manual', help_text='Data source (e.g., manual, API, sensor).', max_length=50)),
                ('farmer', models.ForeignKey(help_text='The farmer who owns this weather record.', on_delete=django.db.models.deletion.CASCADE, related_name='weather_records', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weather_records', to='agri_app.field')),
            ],
            options={
                'verbose_name': 'Weather Record',
                'verbose_name_plural': 'Weather Records',
                'ordering': ['-recorded_at'],
                'unique_together': {('field', 'recorded_at')},
            },
        ),
    ]
