# Generated by Django 6.0 on 2025-12-09 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='date_added',
        ),
        migrations.AddField(
            model_name='crop',
            name='expected_harvest',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='planted_on',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='crop',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Planted'), ('g', 'Growing'), ('r', 'Ready for harvest'), ('h', 'Harvested')], default='p', max_length=20),
        ),
    ]
