# Generated by Django 6.0 on 2025-12-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='farmer',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='farmer',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
