# Generated by Django 6.0 on 2025-12-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherrecord',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('api', 'Weather API'), ('sensor', 'IoT Sensor')], default='manual', help_text='Data source (e.g., manual, API, sensor).', max_length=50),
        ),
    ]
